version: 2
updates:
  # Maintain dependencies for Node.js (backend)
  - package-ecosystem: "npm"
    directory: "/chat-app-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"

  # Maintain dependencies for Node.js (frontend)
  - package-ecosystem: "npm"
    directory: "/chat-app-web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
